### PR TITLE
Fixes #28

### LINKED ISSUE #28: Create file with MSA data for UK
The file TopSkyMSAW.txt to be created to contain the data displayed geographically in the UKAIP at ENR 6-81 (UK Area Minimum Altitudes).

### PR DESCRIPTION
**Pull request by MikePike-collab**
Any correlated tag relating to an aircraft flying IFR below the MSA will show "MSAW" in the top line.
Does not include the MSA sectors defined for airports.
image

### CODE REVIEW

**Comment by luke11brown** [comment]
Hi Mike, this looks good!

Just a couple of requests:

Are you able to put the ALRT field as the first one in each of the tag levels/families? (above the MTCD and release indicator stuff)
Maybe also look at playing with the "default visbility" checkbox in the TAG editor, i.e. it shouldn't appear and indent other items on the line, unless it is actually alerting (I'm not sure if that is the actual function of that checkbox)

**Comment by luke11brown** [comment]
Also, how does this functions with aircraft on approach? does it automatically inhibit if it sees the aircraft is approaching its' ADES?

**Comment by luke11brown** [comment]
As I was messing with tags, I've already added the ALRT fields as required at the top of the tags in 258d01b7dfd35372a366f1952e7357cae4ae01bb

**Comment by MikePike-collab** [comment]
> Also, how does this functions with aircraft on approach? does it automatically inhibit if it sees the aircraft is approaching its' ADES?

No it doesn't as far as I can see. Perhaps there is a way to incorporate step down fixes into the file. I'll look into that.

**Comment by luke11brown** [comment]
Commit a252c7a0a94086b2c329483b4435f4a7e80f8404 adds MSAW file updates ref
https://github.com/luke11brown/UK-TopSky-Controller-Pack/issues/28#issuecomment-707733243

**Comment by luke11brown** [comment]
Also required:
Change defintion of TopSky colour settings:

- [ ] Colour_Warning/Colour_Warning_FL
- [ ] Colour_Urgency/Colour/Urgency_FL
- [ ] Colour_Information/Colour_Information_FL

**Comment by MikePike-collab** [comment]
[TopSkyMSAW.txt](https://github.com/luke11brown/UK-TopSky-Controller-Pack/files/5398192/TopSkyMSAW.txt)
Added FAVAs for all runways. EGBB and EGPF require manual adjustment - to be added.
For complete accuracy longitudes still need to be adjusted based on latitude

**Comment by luke11brown** [comment]
Mike, just awaiting amendments to EGLC FAVA now.

**Comment by MikePike-collab** [comment]
[TopSkyMSAW.txt](https://github.com/luke11brown/UK-TopSky-Controller-Pack/files/5402501/TopSkyMSAW.txt)
Corrected EGLC FAVA definition

**Pull request merged**
